name: cubit-world-tools
main : de.linzn.cubitWorldTools.CubitWorldToolsPlugin
version: ${project.version}
description: An addon for Cubit to manage worlddata
author: Niklas Linz
load: POSTWORLD
depend: [Cubit]
api-version: 1.13
