name: cubit-tools
main : de.linzn.cubitTools.plugin.CubitToolsPlugin
version: ${project.version}
description: An addon for Cubit to manage worldData
author: Niklas Linz
load: POSTWORLD
depend: [Cubit, WorldEdit, WorldGuard]
api-version: 1.13
commands:
   ctools:
      description: CTools command
      usage: /<command>